package cn.com.fuso.cep.test

import cn.com.fusio.event.merge.PinganEduPVEnrich
import java.util.ArrayList

import cn.com.fusio.drools.actions.RuleActionInvoker

// 捕捉行为事件
declare PinganEduPVEnrich
    @role( event )				// role(event|fact)
    @timestamp (eventTime) 	// 将 CEPEvent事实中的 createTime 属性值 ， 赋值给 元数据 @timestamp
//    @duration(7d)			// 设置 事件的持续事件 ， default: duration(0)
//    @expires( 30m )			// 内存管理：当一个事件不再匹配事实，激活规则（有活化的规则），事件自动失效（在 work-memory 中的 保留时长）
end

//============================================== Rules 以用户为中心 ========================================================
rule "test嵌套entity"
    agenda-group "basic_rule"
	when
	    $bd:PinganEduPVEnrich()
	then
		System.out.println($bd) ;
	end

//=================================================== test ==================================================
rule "tags=(安全||健康||保险) & count>2 in a day"
    agenda-group "pingan_breed_demo_test"
    lock-on-active
//    salience 100
    when
        $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("保险","健康","安全"))
        over window:time(1d) from entry-point pingan_breed_demo_test)
    then
        RuleActionInvoker.act_when_AccFre_gt_n($bdList,1);
    end