package cn.com.fuso.cep.expire_day_1

import cn.com.fusio.event.merge.PinganEduPVEnrich
import java.util.ArrayList

import cn.com.fusio.drools.actions.RuleActionInvoker

// 捕捉行为事件
declare PinganEduPVEnrich
    @role( event )				// role(event|fact)
    @timestamp (eventTime) 	// 将 CEPEvent事实中的 createTime 属性值 ， 赋值给 元数据 @timestamp
//    @duration(7d)			// 设置 事件的持续事件 ， default: duration(0)
    @expires( 1d )			// 内存管理：当一个事件不再匹配事实，激活规则（有活化的规则），事件自动失效（在 work-memory 中的 保留时长）
end

//============================================== Rules 以用户为中心 ========================================================
// ==================================================== 产品 ==============================================
// 一、行为积累
// rule01


//二、属性及行为组合
// rule01


//三、指定内容及时触发
// rule01 此处需要 PagePing
rule "阅读某篇文章的浏览时长30秒以上（url）"
  agenda-group "pingan_breed_1day"
     when
         $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("健康") )
         over window:time(7d) from entry-point pingan_breed_1day)
     then
         //count>2
     end




