package cn.com.fuso.cep.product

import cn.com.fusio.event.merge.PinganEduPVEnrich
import java.util.ArrayList

import cn.com.fusio.drools.actions.RuleActionInvoker

// 捕捉行为事件
declare PinganEduPVEnrich
    @role( event )				// role(event|fact)
    @timestamp (eventTime) 	// 将 CEPEvent事实中的 createTime 属性值 ， 赋值给 元数据 @timestamp
//    @duration(7d)			// 设置 事件的持续事件 ， default: duration(0)
    @expires( 30d )			// 内存管理：当一个事件不再匹配事实，激活规则（有活化的规则），事件自动失效（在 work-memory 中的 保留时长）
end

//============================================== Rules 以用户为中心 ========================================================
// ==================================================== 产品 ==============================================
// 一、行为积累
// rule01
//rule "tags=(保险) & count>2 in one week"
//    agenda-group "pingan_breed_edu_pv"
////    salience 100
//    when
//        $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("保险"))
//        over window:time(7d) from entry-point pingan_breed_edu_pv)
//    then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]");
//        //count>2
//        RuleActionInvoker.act_when_AccFre_gt_n($bdList,2);
//    end
//
//// rule02
//rule "tags=(健康) & count>4 in one month"
//    agenda-group "pingan_breed_edu_pv"
//    when
//        $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("健康"))
//        over window:time(30d) from entry-point pingan_breed_edu_pv)
//    then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]") ;
//        //count>4
//        RuleActionInvoker.act_when_AccFre_gt_n($bdList,4);
//    end
//
//// rule03
//rule "count>8 in one month"
//    agenda-group "pingan_breed_edu_pv"
//    when
//        $bdList:ArrayList() from collect ( PinganEduPVEnrich()
//        over window:time(30d) from entry-point pingan_breed_edu_pv)
//    then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]") ;
//        RuleActionInvoker.act_when_AccFre_gt_n($bdList,8);
//    end
//
//
////二、属性及行为组合
//// rule01
//rule "tags=(育儿) & count>3 & age>27 in one week"
//    agenda-group "pingan_breed_edu_pv"
////    salience 100
//    when
//        $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("育儿") ,isAgeGtNum(27))
//        over window:time(7d) from entry-point pingan_breed_edu_pv)
//    then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]");
//        //count>2
//        RuleActionInvoker.act_when_AccFre_gt_n($bdList,3);
//    end
//
//// rule02
// rule "tags=(健康) & count>1 & age>30 in one week"
//     agenda-group "pingan_breed_edu_pv"
//     when
//         $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("健康") ,isAgeGtNum(30))
//         over window:time(7d) from entry-point pingan_breed_edu_pv)
//     then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]");
//         //count>2
//         RuleActionInvoker.act_when_AccFre_gt_n($bdList,1);
//     end
//
//// rule03
// rule "tags=(保险) & count>1 & province(北京|上海|广东|浙江) in one week"
//     agenda-group "pingan_breed_edu_pv"
//     when
//         $bdList:ArrayList() from collect ( PinganEduPVEnrich(containTags("健康") ,isBelongToProvince("北京","上海","广东","浙江 "))
//          over window:time(7d) from entry-point pingan_breed_edu_pv)
//     then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]");
//         //count>2
//         RuleActionInvoker.act_when_AccFre_gt_n($bdList,1);
//     end

//三、指定内容及时触发
// rule01 此处需要 PagePing , 选取page_view后， 30分钟内的同一个session的page_ping，根据个数计算访问时长
rule "url:AccDep>30s"
  agenda-group "pingan_breed_edu_pv_pp"
     when
       $pvEvent :PinganEduPVEnrich(behaviorData.getEvent_name()=="page_view") from entry-point pingan_breed_edu_pv_pp
       $ppList:ArrayList(size() >= 3) from collect (
                  PinganEduPVEnrich(behaviorData.getEvent_name()=="page_ping" ,
                                      behaviorData.getDomain_sessionid() == $pvEvent.getBehaviorData().getDomain_sessionid()  ,
                                      this after[0,30m] $pvEvent)
                  from entry-point pingan_breed_edu_pv_pp
              )
     then
        System.out.println("match:rule=["+drools.getRule().getName()+"]");
        System.out.println(("---->sendEmail to curUserId="+$pvEvent.getBehaviorData().getUserid() +"  accessTime="+$ppList.size()*10+"s"));
//        System.out.println(String.format("event_name=[%s],domain_sessionid=[%s],collector_tstamp=[%s]",
//                                $pvEvent.getBehaviorData().getEvent_name(),
//                                $pvEvent.getBehaviorData().getDomain_sessionid(),
//                                $pvEvent.getBehaviorData().getCollector_tstamp()));
//        $ppList.forEach(x -> {
//            PinganEduPVEnrich bd = (PinganEduPVEnrich)x ;
//            System.out.println(String.format("event_name=[%s],domain_sessionid=[%s],collector_tstamp=[%s]",
//                                                                                 bd.getBehaviorData().getEvent_name(),
//                                                                                 bd.getBehaviorData().getDomain_sessionid(),
//                                                                                 bd.getBehaviorData().getCollector_tstamp()));});
        System.out.println("trigger:action sendEmail ! ");
     end

rule "tags=(健康) & count>1 & province(北京|上海|广东|浙江) in one week"
  agenda-group "pingan_breed_edu_pv"
  when
      $pvEvent: PinganEduPVEnrich(this.containTags("健康","保险","安全","育儿") , this.isBelongToProvince("北京","上海","广东","浙江 ")) from entry-point pingan_breed_edu_pv
      $bdList:ArrayList(size() >= 1) from collect (
            PinganEduPVEnrich(this.containTags("健康","保险","安全","育儿") ,this.isBelongToProvince("北京","上海","广东","浙江 ") ,this.getBehaviorData().getUserid().equals($pvEvent.getBehaviorData().getUserid()) ,this before[0,7d] $pvEvent )
            from entry-point pingan_breed_edu_pv
          )
  then
     System.out.println("match:rule=["+drools.getRule().getName()+"]");
     System.out.println(("---->sendEmail to curUserId="+$pvEvent.toString()));
     for(int i = 0 ; i<$bdList.size() ; i++){
         PinganEduPVEnrich bd = (PinganEduPVEnrich)$bdList.get(i) ;
                         System.out.println(String.format("event_name=[%s],domain_sessionid=[%s],collector_tstamp=[%s]",
                                                                                              bd.getBehaviorData().getEvent_name(),
                                                                                              bd.getBehaviorData().getDomain_sessionid(),
                                                                                              bd.getBehaviorData().getCollector_tstamp()));
     }

      //count>2
//      RuleActionInvoker.act_when_AccFre_gt_n($bdList,1);
  end

//rule "完成了某个表单的测验（url）"
//     agenda-group "pingan_breed_edu_pv_pp"
//     when
//
//     then
//        System.out.println("match:rule=["+drools.getRule().getName()+"]");
//
//         //count>2
//     end
